@URL_BASE=http://localhost:8080

### Obter todas as avaliações
GET {{URL_BASE}}/avaliacao

### Obter avaliação pelo id
GET {{URL_BASE}}/avaliacao/c1db6853-b6f8-479b-b934-0f20e729037e

### Cadastrar uma avaliação
POST {{URL_BASE}}/avaliacao
Content-Type: application/json

{
    "nota": 4.5,
    "reserva": {
        "id": "0df9cfa9-6315-4a62-9799-af13a8ca1c81" 
    } 
}

### Atualizar uma avaliação
PUT {{URL_BASE}}/avaliacao/c391f705-b580-4a65-bf89-dcb34da92e85
Content-Type: application/json

{
    "nota": 4.8
}

### Deletar avaliação pelo id
DELETE {{URL_BASE}}/avaliacao/c1db6853-b6f8-479b-b934-0f20e729037e
