@URL_BASE=http://localhost:8080

### Obter todos os pacotes
GET {{URL_BASE}}/pacote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJpZCI6IjhmMTAzNjNmLTMwMzYtNDgwNS1iMTRmLWQxODVkNzM3NzUzYSIsInVzZXJuYW1lIjoidmFsZW50aW5hMUBnbWFpbC5jb20iLCJpYXQiOjE3MDA2NzI3NTksImV4cCI6MTcwMDY3NjM1OSwiaXNzIjoiVVRGUFIifQ.S2mi7RE_pICci_G6oOhneNMP6p27_TkVi3kKCaAA8QM

### Obter pacote pelo id
GET {{URL_BASE}}/pacote/7097bcc7-1fc3-4813-b70a-5cff770cff3a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJpZCI6IjhmMTAzNjNmLTMwMzYtNDgwNS1iMTRmLWQxODVkNzM3NzUzYSIsInVzZXJuYW1lIjoidmFsZW50aW5hMUBnbWFpbC5jb20iLCJpYXQiOjE3MDA2NzI3NTksImV4cCI6MTcwMDY3NjM1OSwiaXNzIjoiVVRGUFIifQ.S2mi7RE_pICci_G6oOhneNMP6p27_TkVi3kKCaAA8QM

### Cadastrar um pacote
POST {{URL_BASE}}/pacote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJpZCI6IjhmMTAzNjNmLTMwMzYtNDgwNS1iMTRmLWQxODVkNzM3NzUzYSIsInVzZXJuYW1lIjoidmFsZW50aW5hMUBnbWFpbC5jb20iLCJpYXQiOjE3MDA2NzI3NTksImV4cCI6MTcwMDY3NjM1OSwiaXNzIjoiVVRGUFIifQ.S2mi7RE_pICci_G6oOhneNMP6p27_TkVi3kKCaAA8QM
Content-Type: application/json

{
    "descricao": "Pacote de Praia",
    "preco": 500.0,
    "passeiosIds" : ["9ec90033-acc8-4ea1-ad5e-1cf57c1f74ad"]
}

### Atualizar um pacote
PUT {{URL_BASE}}/pacote/6facdf63-51e0-4f97-97b2-af8c0a4c786d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJpZCI6IjhmMTAzNjNmLTMwMzYtNDgwNS1iMTRmLWQxODVkNzM3NzUzYSIsInVzZXJuYW1lIjoidmFsZW50aW5hMUBnbWFpbC5jb20iLCJpYXQiOjE3MDA2NzI3NTksImV4cCI6MTcwMDY3NjM1OSwiaXNzIjoiVVRGUFIifQ.S2mi7RE_pICci_G6oOhneNMP6p27_TkVi3kKCaAA8QM
Content-Type: application/json

{
    "descricao": "Pacote de Montanha",
    "preco": 600.0
}

### Deletar pacote pelo id
DELETE {{URL_BASE}}/pacote/7097bcc7-1fc3-4813-b70a-5cff770cff3a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJpZCI6IjhmMTAzNjNmLTMwMzYtNDgwNS1iMTRmLWQxODVkNzM3NzUzYSIsInVzZXJuYW1lIjoidmFsZW50aW5hMUBnbWFpbC5jb20iLCJpYXQiOjE3MDA2NzI3NTksImV4cCI6MTcwMDY3NjM1OSwiaXNzIjoiVVRGUFIifQ.S2mi7RE_pICci_G6oOhneNMP6p27_TkVi3kKCaAA8QM
