@URL_BASE=http://localhost:8080

### Obter todos os pagamentos
GET {{URL_BASE}}/pagamento

### Obter pagamento pelo id
GET {{URL_BASE}}/pagamento/acdb68da-3579-42e5-82c0-1a5d57b12f13

### Cadastrar um pagamento
POST {{URL_BASE}}/pagamento
Content-Type: application/json

{
    "valor": 100.0,
    "reserva": {
        "id": "0df9cfa9-6315-4a62-9799-af13a8ca1c81"
    }
}

### Atualizar um pagamento
PUT {{URL_BASE}}/pagamento/907503c2-531e-45f5-ad69-9aead1127ac3
Content-Type: application/json

{
    "valor": 150.0
}

### Deletar pagamento pelo id
DELETE {{URL_BASE}}/pagamento/907503c2-531e-45f5-ad69-9aead1127ac3
