@URL_BASE=http://localhost:80/api/core

### Obter todos os passeios
GET {{URL_BASE}}/passeio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJpZCI6ImI4MTM3YmUyLTEyMWUtNDMwNy05NDY5LTc4MDM2MjY2ZDI2ZSIsInVzZXJuYW1lIjoidmFsZW50aW5hQGdtYWlsLmNvbSIsImlhdCI6MTcwMjU3NzM0OCwiZXhwIjoxNzAyNTgwOTQ4LCJpc3MiOiJVVEZQUiJ9.es-BzT-hTXUPo5Cipr8H3Zim9NenVpKJL_UvXzKWED4


### Obter passeio pelo id
GET {{URL_BASE}}/passeio/2b0f4946-c131-44e5-9dc9-2c3dfce5e370
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJpZCI6ImI4MTM3YmUyLTEyMWUtNDMwNy05NDY5LTc4MDM2MjY2ZDI2ZSIsInVzZXJuYW1lIjoidmFsZW50aW5hQGdtYWlsLmNvbSIsImlhdCI6MTcwMjU3NzM0OCwiZXhwIjoxNzAyNTgwOTQ4LCJpc3MiOiJVVEZQUiJ9.es-BzT-hTXUPo5Cipr8H3Zim9NenVpKJL_UvXzKWED4

### Cadastrar um passeio
POST {{URL_BASE}}/passeio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJpZCI6ImI4MTM3YmUyLTEyMWUtNDMwNy05NDY5LTc4MDM2MjY2ZDI2ZSIsInVzZXJuYW1lIjoidmFsZW50aW5hQGdtYWlsLmNvbSIsImlhdCI6MTcwMjU3NzM0OCwiZXhwIjoxNzAyNTgwOTQ4LCJpc3MiOiJVVEZQUiJ9.es-BzT-hTXUPo5Cipr8H3Zim9NenVpKJL_UvXzKWED4
Content-Type: application/json

{
    "destino": "Praia de Copacabana",
    "itinerario": "Passeio à beira-mar",
    "preco": 50.0
}

### Atualizar um passeio
PUT {{URL_BASE}}/passeio/2b0f4946-c131-44e5-9dc9-2c3dfce5e370
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJpZCI6ImI4MTM3YmUyLTEyMWUtNDMwNy05NDY5LTc4MDM2MjY2ZDI2ZSIsInVzZXJuYW1lIjoidmFsZW50aW5hQGdtYWlsLmNvbSIsImlhdCI6MTcwMjU3NzM0OCwiZXhwIjoxNzAyNTgwOTQ4LCJpc3MiOiJVVEZQUiJ9.es-BzT-hTXUPo5Cipr8H3Zim9NenVpKJL_UvXzKWED4
Content-Type: application/json

{
    "destino": "Praia de Ipanema",
    "itinerario": "Passeio pelo calçadão",
    "preco": 60.0
}

### Deletar passeio pelo id
DELETE {{URL_BASE}}/passeio/397e0894-ec13-469d-bc8f-affc733bd1fc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJpZCI6ImI4MTM3YmUyLTEyMWUtNDMwNy05NDY5LTc4MDM2MjY2ZDI2ZSIsInVzZXJuYW1lIjoidmFsZW50aW5hQGdtYWlsLmNvbSIsImlhdCI6MTcwMjU3NzM0OCwiZXhwIjoxNzAyNTgwOTQ4LCJpc3MiOiJVVEZQUiJ9.es-BzT-hTXUPo5Cipr8H3Zim9NenVpKJL_UvXzKWED4
