@URL_BASE=http://localhost:8080

### Obter todos os passeios
GET {{URL_BASE}}/passeio

### Obter passeio pelo id
GET {{URL_BASE}}/passeio/32db2106-a53b-48d4-8194-e694552492e7

### Cadastrar um passeio
POST {{URL_BASE}}/passeio
Content-Type: application/json

{
    "destino": "Praia de Copacabana",
    "itinerario": "Passeio à beira-mar",
    "preco": 50.0
}

### Atualizar um passeio
PUT {{URL_BASE}}/passeio/e3de1066-dd32-4630-87e0-dae10f34032b
Content-Type: application/json

{
    "destino": "Praia de Ipanema",
    "itinerario": "Passeio pelo calçadão",
    "preco": 60.0
}

### Deletar passeio pelo id
DELETE {{URL_BASE}}/passeio/e3de1066-dd32-4630-87e0-dae10f34032b
