@URL_BASE=http://localhost:8080


### Obter todas as pessoas paginado
GET {{URL_BASE}}/pessoa/pages?size=20&page=0&sort=email&direction=DESC

### Obter todas as pessoas
GET {{URL_BASE}}/pessoa


### Obter pessoa pelo id
GET {{URL_BASE}}/pessoa/9fa00dac-54d9-4ecb-a137-8cb9e78898f8

### Cadastrar 1 pessoa
POST {{URL_BASE}}/pessoa
Content-Type: application/json

{
    "nome": "Valentina",
    "email": "valentina1@gmail.com",
    "nascimento": "1960-01-01T00:00:00",
    "password": "123456"
}

### Atualizar 1 pessoa
PUT {{URL_BASE}}/pessoa/9fa00dac-54d9-4ecb-a137-8cb9e78898f8
Content-Type: application/json

{
    "nome": "Jose",
    "email": "jose@gmail.com",
    "nascimento": "1960-01-01T00:00:00",
    "senha": "123456",
}

### Deletar pessoa pelo id
DELETE {{URL_BASE}}/pessoa/1a668100-9c62-4f4d-ab91-99f87f072b00