@URL_BASE=http://localhost:8080

### Obter todas as reservas
GET {{URL_BASE}}/reserva

### Obter reserva pelo id
GET {{URL_BASE}}/reserva/c1db6853-b6f8-479b-b934-0f20e729037e

### Cadastrar uma reserva
POST {{URL_BASE}}/reserva
Content-Type: application/json

{
    "data": "2023-09-30T14:30:00",
    "pacote": {
        "id": "e67fa705-0e16-43c4-820b-70c6b5e98a5c"
    },
    "person": {
        "id": "b173bbdf-df2a-4b9d-9151-c28d298772a1"
    }
}

### Atualizar uma reserva
PUT {{URL_BASE}}/reserva/c1db6853-b6f8-479b-b934-0f20e729037e
Content-Type: application/json

{
    "data": "2023-10-15T10:00:00"
}

### Deletar reserva pelo id
DELETE {{URL_BASE}}/reserva/c1db6853-b6f8-479b-b934-0f20e729037e
